### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by ZhouCX117** [yue-zhongqi/diti#1]
Excellent work! Can't wait to read the code!

**Comment by yue-zhongqi** [comment]
Thanks for your interest. We have released our code.

**Comment by ZhouCX117** [comment]
Thanks a lot!

**Comment by ZhouCX117** [comment]
By the way, where can I find the pretrained dpm models for lfw datasets?

**Comment by yue-zhongqi** [comment]
LFW is only used for evaluation. So there is no pretrained dpm model on it.
